name: Deploy to github pages
on:
  push:
    branches:
      - master
jobs:
  gh-pages-deploy:
    - name: Setup Node.js for use with actions
      uses: actions/setup-node@v1.1.0
      with:
        version:  12.x
    - name: Checkout branch
      uses: actions/checkout@v2

    - name: Clean install dependencies
      run: npm ci

    - name:
      run: |
        git config user.name "GitHub Actions" && git config user.email "actions@users.noreply.github.com"
        npm run gh-pages-deploy